project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - project-log.qmd
    - wikidata.qmd
    - wikidata-item.ipynb
    - timeline.qmd

author: 
  - name: Nala Freundlich
  - orcid: 0009-0000-5538-453X
  - affiliation: HsH
  
website:
  title: "BIM Prototype 02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project-log.qmd
        text: Project Log
      - href: wikidata.qmd
        text: Wikidata
      - href: wikidata-item.ipynb
        text: Item Profile
      - href: timeline.qmd
        text: "Austellungen Timelines"

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
